# Generated by Django 3.2.25 on 2024-03-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_processedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumers',
            name='client_reference_no',
            field=models.CharField(max_length=255),
        ),
    ]
